spring:
  application:
    name: consulta-creditos
  datasource:
    url: jdbc:postgresql://localhost:5430/gestionna
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        schema: public
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
