spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/gestionna}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-creditos:9092}
