spring:
  application:
    name: consulta-creditos
  datasource:
    url: jdbc:postgresql://localhost:5430/gestionna
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
